// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {desktop} from '../models';
import {store} from '../models';
import {domain} from '../models';

export function CancelFetch():Promise<string>;

export function Context():Promise<context.Context>;

export function GetJob(arg1:number):Promise<desktop.JobDetail>;

export function GetProgress():Promise<desktop.ProgressView>;

export function GetStats():Promise<store.Stats>;

export function ListJobs(arg1:desktop.ListFilter):Promise<desktop.JobListResult>;

export function LogInfo(arg1:string):Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function RunNow():Promise<desktop.RunResult>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateStatus(arg1:number,arg2:string):Promise<domain.Job>;
