// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFetch() {
  return window['go']['desktop']['App']['CancelFetch']();
}

export function Context() {
  return window['go']['desktop']['App']['Context']();
}

export function GetJob(arg1) {
  return window['go']['desktop']['App']['GetJob'](arg1);
}

export function GetProgress() {
  return window['go']['desktop']['App']['GetProgress']();
}

export function GetStats() {
  return window['go']['desktop']['App']['GetStats']();
}

export function ListJobs(arg1) {
  return window['go']['desktop']['App']['ListJobs'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['desktop']['App']['LogInfo'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['desktop']['App']['OpenInBrowser'](arg1);
}

export function RunNow() {
  return window['go']['desktop']['App']['RunNow']();
}

export function Shutdown(arg1) {
  return window['go']['desktop']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['desktop']['App']['Startup'](arg1);
}

export function UpdateStatus(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateStatus'](arg1, arg2);
}
